id: I2325A3B9
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T13:11:22+00:00'
last_modified: '2022-06-07T10:37:38.670419+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W8464
  title: རོང་སྟོན་ཤེས་བྱ་ཀུན་རིག་གི་རྒྱུད་བླ་མའི་འགྲེལ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6180':
      image_group_id: I1KG12615
      title: Volume 1 of rong ston shes bya kun rig gi rgyud bla ma'i 'grel pa/
      total_pages: 202
      order: 1
      base_file: 6180.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
